### ISSUE TITLE
Confirm Steps - model and cache directories

### ISSUE THREAD

**Issue by AusAgentSmith** [qdm12/private-gpt#7]
Hi qdm, i am pretty new to this, but semi handy with linux and docker.

Can i suggest you make your guide work "as is" without requiring a user to make adjustments.

Suspect there is a bug somewhere re installing extras ui? 

**When i run your config as is following these steps, i run into this issue;**

1. git clone -b docker-tip https://github.com/qdm12/private-gpt.git
2. docker build -t privategpt --build-arg POETRY_EXTRAS="ui vector-stores-qdrant embeddings-huggingface" https://github.com/qdm12/private-gpt.git#docker-tip
3. docker compose up --build

```
[ollama-1       | Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
ollama-1       | Your new public key is:
ollama-1       |
ollama-1       | ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJJubtpdzJa8cTd35xKZBLJEDgZ7ZkU5bS8jUEm+W3B7
ollama-1       |
ollama-1       | time=2024-04-04T09:31:43.862Z level=INFO source=images.go:804 msg="total blobs: 0"
ollama-1       | time=2024-04-04T09:31:43.862Z level=INFO source=images.go:811 msg="total unused blobs removed: 0"
ollama-1       | time=2024-04-04T09:31:43.862Z level=INFO source=routes.go:1118 msg="Listening on [::]:11434 (version 0.1.30)"
ollama-1       | time=2024-04-04T09:31:43.862Z level=INFO source=payload_common.go:113 msg="Extracting dynamic libraries to /tmp/ollama4038103232/runners ..."
private-gpt-1  | 09:31:44.189 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'docker']
ollama-1       | time=2024-04-04T09:31:45.603Z level=INFO source=payload_common.go:140 msg="Dynamic LLM libraries [cpu_avx rocm_v60000 cuda_v11 cpu cpu_avx2]"
ollama-1       | time=2024-04-04T09:31:45.603Z level=INFO source=gpu.go:115 msg="Detecting GPU type"
ollama-1       | time=2024-04-04T09:31:45.603Z level=INFO source=gpu.go:265 msg="Searching for GPU management library libcudart.so*"
ollama-1       | time=2024-04-04T09:31:45.603Z level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [/tmp/ollama4038103232/runners/cuda_v11/libcudart.so.11.0]"
ollama-1       | time=2024-04-04T09:31:45.604Z level=INFO source=gpu.go:340 msg="Unable to load cudart CUDA management library /tmp/ollama4038103232/runners/cuda_v11/libcudart.so.11.0: cudart init failure: 35"
ollama-1       | time=2024-04-04T09:31:45.604Z level=INFO source=gpu.go:265 msg="Searching for GPU management library libnvidia-ml.so"
ollama-1       | time=2024-04-04T09:31:45.604Z level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
ollama-1       | time=2024-04-04T09:31:45.604Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
ollama-1       | time=2024-04-04T09:31:45.604Z level=INFO source=routes.go:1141 msg="no GPU detected"
private-gpt-1  | Traceback (most recent call last):
private-gpt-1  |   File "/home/worker/app/private_gpt/launcher.py", line 57, in create_app
private-gpt-1  |     from private_gpt.ui.ui import PrivateGptUi
private-gpt-1  |   File "/home/worker/app/private_gpt/ui/ui.py", line 10, in <module>
private-gpt-1  |     import gradio as gr  # type: ignore
private-gpt-1  |     ^^^^^^^^^^^^^^^^^^^
private-gpt-1  | ModuleNotFoundError: No module named 'gradio'
private-gpt-1  |
private-gpt-1  | The above exception was the direct cause of the following exception:
private-gpt-1  |
private-gpt-1  | Traceback (most recent call last):
private-gpt-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
private-gpt-1  |   File "<frozen runpy>", line 88, in _run_code
private-gpt-1  |   File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
private-gpt-1  |     from private_gpt.main import app
private-gpt-1  |   File "/home/worker/app/private_gpt/main.py", line 6, in <module>
private-gpt-1  |     app = create_app(global_injector)
private-gpt-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
private-gpt-1  |   File "/home/worker/app/private_gpt/launcher.py", line 59, in create_app
private-gpt-1  |     raise ImportError(
private-gpt-1  | ImportError: UI dependencies not found, install with `poetry install --extras ui`
private-gpt-1 exited with code 1
](url)
```

**Comment by qdm12** [comment]
Are you sure you are using the image you built?

```
ImportError: UI dependencies not found, install with `poetry install --extras ui`
```

So it looks like the `ui` wasn't part of the image built, despite the correct POETRY_EXTRAS you used. Maybe try building it with another image name to make sure you run the right image?

**Comment by AusAgentSmith** [comment]
Fixed using your updated steps from today.
